config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  devise_for :users

  resources :users, only: [:update] do
    member { post :toggle_active }
    collection do
      get :edit_password
    end
  end

  resources :supporters, except: [:destroy]
  resources :managers, except: [:destroy]

  resources :locations
  resources :harvests
  resources :offerings do
    member do
      post :publish
      get :print
    end
  end
end

app/models/offering.rb
class Offering < ApplicationRecord
  belongs_to :location
  has_many :offers, dependent: :destroy
  has_many :harvests
  has_many :harvested_products, through: :harvests

  validates :closes_at, presence: true

  scope :not_closed, -> { where("closes_at > ?", Time.zone.now) }
  scope :by_location, -> (location) { where(location: location) }
  scope :published, -> { where(published: true) }
  scope :active, -> { not_closed.published }

  accepts_nested_attributes_for :offers, allow_destroy: true, reject_if: :all_blank

  def harvested_by(user)
    harvests.by_user(user).last
  end

  def status
    return 'Encerrada' if closed?
    published ? 'Publicada' : 'Não publicada'
  end

  def offers_list
    offers.with_amount.product_names
  end

  def closed?
    Time.zone.now > closes_at
  end

  def available_amount_for(product_name)
    offers.where(product_name: product_name).sum(:amount) -
    harvested_products.where(product_name: product_name).sum(:amount)
  end

  def closes_at_date=(date)
    @closes_at_date = date
    set_closes_at
    date
  end

  def closes_at_time=(time)
    @closes_at_time = "#{time.values[3]}:#{time.values[4]}"
    set_closes_at
    time
  end

  def closes_at_date
    closes_at&.strftime('%d-%m-%Y')
  end

  def closes_at_time
    closes_at
  end

  def publish!
    update!(published: true)
  end

  def total_harvested
    harvested_products.sum(:amount)
  end

private

    def set_closes_at
      if @closes_at_date && @closes_at_time
        self.closes_at = Time.zone.parse("#{@closes_at_date} #{@closes_at_time}")
      end
    end
end

app/controllers/offerings_controller.rb
class OfferingsController < ApplicationController
  before_action :ensure_manager
  before_action :set_offering, only: %i[ show edit update destroy publish print]

  # GET /offerings or /offerings.json
  def index
    @offerings = Offering.order(closes_at: :desc)
  end

  # GET /offerings/1 or /offerings/1.json
  def show
    @offer = @offering.offers.build
  end

  # GET /offerings/new
  def new
    @offering = Offering.new(offers: Offer.default_set)
  end

  # GET /offerings/1/edit
  def edit
  end

  # POST /offerings or /offerings.json
  def create
    @offering = Offering.new(offering_params)

    respond_to do |format|
      if @offering.save
        format.html { redirect_to @offering, notice: "Offering was successfully created." }
        format.json { render :show, status: :created, location: @offering }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @offering.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offerings/1 or /offerings/1.json
  def update
    respond_to do |format|
      if @offering.update(offering_params)
        format.html { redirect_to @offering, notice: "Offering was successfully updated." }
        format.json { render :show, status: :ok, location: @offering }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @offering.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offerings/1 or /offerings/1.json
  def destroy
    @offering.destroy
    respond_to do |format|
      format.html { redirect_to offerings_url, notice: "Offering was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def publish
    @offering.publish!
    redirect_to @offering, notice: "Oferenda publicada com sucesso."
  end

  def print
  end

  private

    def ensure_manager
      raise ActiveRecord::RecordNotFound if !current_user.manager?
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_offering
      @offering = Offering.includes(:offers).find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def offering_params
      params.require(:offering).permit(
        :location_id, :closes_at_date, :closes_at_time, :closes_at,
        offers_attributes: [:id, :product_name, :amount, :_destroy]
      )
    end
end

app/helpers/offerings_helper.rb
module OfferingsHelper

  def seven_days_from_now
    (Time.zone.today..Time.zone.today + 7).map do |day|
      [I18n.l(day, format: '%A, %d/%m'), day.strftime('%d-%m-%Y')]
    end
  end

  def publish_button_class(offering)
    'disabled' if offering.closed? || offering.published
  end

  def ordered_products(products)
    products.sort { |a, b| a.product_name <=> b.product_name }
  end

  def products_and_count(harvest)
    harvest.harvested_products.with_amount.map do |hp|
      "#{hp.product_name} (#{hp.amount})"
    end.join(', ')
  end

  def harvests_total(harvested_products)
    harvested_products.group_by(&:product_name).map do |product_name, group|
      "#{product_name} (#{group.reduce(0){ |sum, hp| sum + hp.amount.to_i }})"
    end.join(', ')
  end
end

app/views/offerings/_form.html.erb
<%= form_with(model: offering) do |form| %>
  <% if offering.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offering.errors.count, "error") %> prohibited this offering from being saved:</h2>

      <ul>
        <% offering.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row g-3 pb-3">
    <div class="col-md-5">
      <%= form.label :location_id, 'Local de colheita', class: "form-label" %>
      <%= form.collection_select(:location_id, Location.all, :id, :name, {prompt: false }, { class: 'form-select' }) %>
    </div>
    <div class="col-md-4">
      <%= form.label :closes_at_date, 'Encerra em', class: "form-label" %>
      <%= form.select :closes_at_date, seven_days_from_now, { prompt: false }, { class: "form-select", "aria-label" => 'Encerra em' } %>
    </div>
    <div class="col-md-3">
      <%= form.label :closes_at_time, 'Encerra às', class: "form-label" %>
      <%= form.time_select :closes_at_time, {minute_step: 15, start_hour: 8, end_hour: 20, time_separator: ''}, { class: "form-select", "aria-label" => 'Encerra às' } %>
    </div>
  </div>

  <h5 class="h5">Produtos disponíveis</h5>

  <div class="row h6 mt-3">
    <div class="field col-5">
      Produto
    </div>
    <div class="field col-4">
      Quantidade disponível
    </div>
  </div>

  <div id='offers' class="row g-3 pb-3">
    <%= form.fields_for :offers, ordered_products(form.object.offers) do |offer_form| %>
      <%= render 'offer_fields', form: offer_form %>
    <% end %>
  </div>

  <div class="actions text-right">
    <%= link_to_add_nested(form, :offers, '#offers',
      link_classes: 'btn btn-secondary',
      link_text: 'Adicionar produto'
    ) %>

    <%= form.submit submit_label, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/offerings/_offer_fields.html.erb
<div class="col-5">
  <%= form.label :product_name, 'Nome do produto', class: "form-label sr-only", placeholder: "Produto" %>
  <%= form.text_field :product_name, class: "form-control", placeholder: 'Produto' %>
</div>
<div class="field col-4">
  <%= form.label :amount, "Quantidade", class: "form-label sr-only" %>
  <%= form.number_field :amount, class: "form-control", placeholder: "Quantidade" %>
</div>
<div class="field col-3">
  <%= form.label :_destroy  do %>
    <%= form.check_box :_destroy %> Remover produto
  <% end %>
</div>

app/views/offerings/edit.html.erb
<p id="notice"><%= notice %></p>

<div class="navbar mb-3">
  <div class="h3">
    Editar Oferenda
  </div>

  <div class="float-right">
    <%= link_to "Voltar", offerings_path, class: "btn btn-secondary" %>
  </div>
</div>

<%= render 'form', offering: @offering, submit_label: 'Salvar' %>

app/views/offerings/index.html.erb
<p id="notice"><%= notice %></p>

<div class="mt-3">
  <div class="float-left h3">
    Oferendas
  </div>

  <div class='float-right'>
    <%= link_to 'Nova oferenda', new_offering_path, class: 'btn btn-primary' %>
    <%= link_to 'Voltar', root_path, class: 'btn btn-secondary' %>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Local de Colheita</th>
      <th scope="col">Encerra em</th>
      <th scope="col">Status</th>
      <th scope="col">Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @offerings.each do |offering| %>
      <tr>

        <th scope="row">
          <%= link_to offering do %>
            <%= offering.location&.name %>
          <% end %>
        </th>
        <td><%= I18n.l(offering.closes_at, format: '%d/%m - %A, %H:%M') %></td>
        <td><%= offering.status %></td>
        <td>
          <u><%= link_to 'Visualizar', offering %></u>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/offerings/new.html.erb
<div class="navbar">
  <div class="h3 float-left">
    Nova Oferenda
  </div>

  <%= link_to 'Voltar', offerings_path, class: 'btn btn-secondary float-right' %>
</div>


<%= render 'form', offering: @offering, submit_label: 'Salvar' %>

app/views/offerings/print.html.erb
<% @offering.harvests.ordered_by_user.each do |harvest| %>
  <p>
    <b><%= harvest.user.full_name %>:</b> <%= products_and_count(harvest) %>
  </p>
<% end %>
</br>
<hr>
<p><b>Resumo</b></p>
<p><%= harvests_total(@offering.harvested_products) %>
</br></br>
<p><b>Total de itens:</b> <%= @offering.total_harvested %></p>

app/views/offerings/show.html.erb
<p id="notice"><%= notice %></p>

<div class="navbar mb-3">
  <div class="h3">
    Detalhes da Oferenda
  </div>

  <div class="float-right">
    <div class="float-left mr-1">
      <%= button_to "Publicar", publish_offering_path(@offering), class: "btn btn-primary float-right #{publish_button_class(@offering)}" %>
      <%= link_to "Imprimir", print_offering_path(@offering), class: "btn btn-primary float-right", target: '_blank' %>
    </div>
    <%= link_to "Editar", edit_offering_path(@offering), class: "btn btn-secondary btn-md btn-block" %>
    <%= link_to "Voltar", offerings_path, class: "btn btn-secondary" %>
  </div>
</div>

<div class="row g-3 pb-3 border-bottom">
  <div class="col-md-4">
    <label for="location_id" class="form-label">Local de Colheita</label>
    <input type="text" readonly class="form-control" id="location_id" value="<%= @offering.location.name %>">
  </div>
  <div class="col-md-4">
    <label for="closes_at" class="form-label">Encerra em</label>
    <input type="text" readonly class="form-control" id="closes_at" value="<%= I18n.l(@offering.closes_at, format: "%d/%m (%A) às %H:%M") %>">
  </div>
  <div class="col-md-4">
    <label for="status" class="form-label">Status</label>
    <input type="text" readonly class="form-control" id="status" value="<%= @offering.status %>">
  </div>
</div>

<h5 class="h5 mt-3">
  Produtos disponíveis
</h5>

<table class="table table-striped table-sm text-center">
  <thead>
    <tr>
      <th scope="col">Produto</th>
      <th scope="col">Quantidade</th>
    </tr>
  </thead>

  <tbody>
    <% @offering.offers.with_amount.order(product_name: :asc).each do |offer| %>
      <tr>
        <th scope="row">
          <%= offer.product_name %>
        </th>
        <td><%= offer.amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>