config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  devise_for :users

  resources :users, only: [:update] do
    member { post :toggle_active }
    collection do
      get :edit_password
    end
  end

  resources :supporters, except: [:destroy]
  resources :managers, except: [:destroy]

  resources :locations
  resources :harvests
  resources :offerings do
    member do
      post :publish
      get :print
    end
  end
end

app/models/manager.rb
class Manager < User

  default_scope { where("role != 'supporter'") }
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  def index
    @users = Manager.order(first_name: :asc)
  end

  def show
  end

  def new
    @user = Manager.new
  end

  def edit
  end

  def create
    @user = Manager.new(manager_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to managers_path, notice: "Gestor adicionar com sucesso." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(manager_params)
        format.html { redirect_to managers_path, notice: "Gestor atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = Manager.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def manager_params
      params.require(:manager).permit(
        :first_name, :last_name, :email, :location_id, :items_per_harvest, :role
      )
    end
end

app/views/managers/_form.html.erb
<%= form_with model: user do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row g-3 pb-3">
    <div class="col-md-4">
      <%= form.label :first_name, 'Nome', class: "form-label" %>
      <%= form.text_field :first_name, class: "form-control",
        placeholder: "Nome", 'aria-label' => "Nome" %>
    </div>
    <div class="col-md-4">
      <%= form.label :last_name, 'Sobrenome', class: "form-label" %>
      <%= form.text_field :last_name, class: "form-control",
        placeholder: "Sobrenome", 'aria-label' => "Sobrenome" %>
    </div>
    <div class="col-md-4">
      <%= form.label :active, 'Status', class: "form-label" %>
      <%= form.text_field :active, class: "form-control", readonly: true, 'aria-label' => "Active", value: user_status(user.active) %>
    </div>
    <div class="col-md-6">
      <%= form.label :role, 'Atribuição', class: "form-label" %>
      <%= form.select :role, role_positions, { pompt: false }, class: "form-select", 'aria-label' => "Atribuição" %>
    </div>
    <div class="col-md-6">
      <%= form.label :email, 'E-mail', class: "form-label" %>
      <%= form.text_field :email, class: "form-control",
        placeholder: "E-mail", 'aria-label' => "E-mail" %>
    </div>
    <div class="col-md-6">
      <%= form.label :location_id, 'Local de colheita', class: "form-label" %>
      <%= form.collection_select(:location_id, Location.all, :id, :name, {prompt: 'Escolha um local de colheita'}, { class: 'form-select' }) %>
    </div>
    <div class="col-md-6">
      <%= form.label :items_per_harvest, 'Itens por colheita', class: "form-label" %>
      <%= form.number_field :items_per_harvest, min: 1, class: "form-control",
        placeholder: "Itens por colheita", 'aria-label' => "E-mail" %>
    </div>
  </div>

  <div class="actions text-right">
    <%= form.submit 'Salvar gestor', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/managers/edit.html.erb
<div class="navbar">
  <div class="h3 float-left">
    Editar Gestor
  </div>

  <div class='float-right'>
    <div class="float-left mr-1">
      <%= button_to( status_button_label(@user.active),
        toggle_active_user_path(@user),
        class: 'btn btn-primary'
      ) %>
    </div>
    <%= link_to 'Voltar', managers_path, class: 'btn btn-secondary' %>
  </div>
</div>

<%= render 'form', user: @user %>

app/views/managers/index.html.erb
<p id="notice"><%= notice %></p>

<div class="mt-3">
  <div class="float-left h3">
    Gestores
  </div>

  <div class='float-right'>
    <%= link_to 'Novo gestor', new_manager_path, class: 'btn btn-primary' %>
    <%= link_to 'Voltar', root_path, class: 'btn btn-secondary' %>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">Atribuição</th>
      <th scope="col">Local de Colheita</th>
      <th scope="col-sm-1">Itens</th>
      <th scope="col-sm-1">Status</th>
      <th scope="col">Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <th scope="row"><%= user.full_name %></th>
        <th scope="col"><%= role_label(user.role) %></th>
        <td><%= user.location&.name %></td>
        <td><%= user.items_per_harvest %></td>
        <td><%= user_status(user.active) %></td>
        <td><u><%= link_to 'Editar', edit_manager_path(user) %></u></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/managers/new.html.erb
<div class="navbar">
  <div class="h3 float-left">
    Novo Gestor
  </div>

  <%= link_to 'Voltar', managers_path, class: 'btn btn-secondary float-right' %>
</div>

<%= render 'form', user: @user %>