config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  devise_for :users

  resources :users, only: [:update] do
    member { post :toggle_active }
    collection do
      get :edit_password
    end
  end

  resources :supporters, except: [:destroy]
  resources :managers, except: [:destroy]

  resources :locations
  resources :harvests
  resources :offerings do
    member do
      post :publish
      get :print
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper

  def harvest_button
    return disabled_button if !current_offering
    current_harvest ? edit_harvest_button : new_harvest_button
  end

  def disabled_button
    link_to('Não há oferendas disponíveis', '#',
      class: "btn btn-sm btn-block btn-primary mb-3 disabled"
    )
  end

  def new_harvest_button
    link_to('Realizar Pedido',
      new_harvest_url,
      class: "btn btn-sm btn-block btn-primary mb-3"
    )
  end

  def edit_harvest_button
    link_to('Editar pedido realizado',
      edit_harvest_url(current_harvest),
      class: "btn btn-sm btn-block btn-primary mb-3"
    )
  end
end

app/views/welcome/index.html.erb
Olá, <%= current_user.first_name %>. O que gostaria de fazer?

</br>
</br>


<ul class="text-center">
  <!-- li>
    <%= link_to 'Gerenciar locais de colheita', locations_url,
      class: 'btn btn-sm btn-block btn-primary mb-3' %>
  </li -->

  <% if !current_user.supporter? %>
    <li>
      <%= link_to 'Gerenciar oferendas', offerings_url,
        class: 'btn btn-sm btn-block btn-primary  mb-3' %>
    </li>

    <li>
      <%= link_to 'Gerenciar apoiadores',
        supporters_url,
        class: 'btn btn-sm btn-block btn-primary mb-3' %>
    </li>

    <li>
      <%= link_to 'Gerenciar gestores',
        managers_url,
        class: 'btn btn-sm btn-block btn-primary mb-3' %>
    </li>
  <% end %>

  <li><%= harvest_button %></li>

  <% if current_user.harvests.last %>
    <li>
      <%= link_to 'Ver último pedido realizado',
        current_user.harvests.last,
        class: 'btn btn-sm btn-block btn-primary mb-3' %>
    </li>
  <% end %>

  <li>
    <%= link_to 'Editar senha',
      edit_password_users_url,
      class: 'btn btn-sm btn-block btn-primary mb-3' %>
  </li>

</ul>

<%= button_to "Sair", destroy_user_session_url, data: { confirm: "Tem certeza que deseja sair?" }, method: :delete, class: 'btn btn-lg btn-block' %>